@baseUrl = http://localhost:8081
@traceId = 4bf92f3577b34da6a3ce929d0e0e4737
@parentSpanId = 00f067aa0ba902b7
# Users request in shared trace

GET {{baseUrl}}/api/users/123?trace_id={{traceId}}&parent_span_id={{parentSpanId}}
Accept: application/json

### Orders request in shared trace
GET {{baseUrl}}/api/orders/456?trace_id={{traceId}}&parent_span_id={{parentSpanId}}
Accept: application/json

### Checkout request in shared trace
POST {{baseUrl}}/api/checkout?trace_id={{traceId}}&parent_span_id={{parentSpanId}}
Content-Type: application/json
Accept: application/json

{
  "cart_id": "cart-123",
  "payment_method": "visa",
  "items": [
    {
      "sku": "laptop-001",
      "qty": 1
    },
    {
      "sku": "mouse-002",
      "qty": 2
    }
  ]
}
